name: GitHub Actions Demo
on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
env:
    My_HOST: '127.0.0.1'
    COMPANY_NAME: 'CCT'
   


jobs:
    build-job:
        runs-on: ubuntu-latest
        env:
            FULLNAME: 'Tikkkimo'
        steps:
           
            - run: echo ${{ env.COMPANY_NAME }}
            - run: echo ${{ vars.COMPANY_NAME}}
            - run: echo ${{ secrets.MYSQL_PASSWORD }}
            - run: echo "My host is $My_HOST and $FULLNAME $COMPANY_NAME"
            - run: echo "Hello ${{github.actor}}" $FULLNAME
    test-job:
        runs-on: ubuntu-latest
        needs: build-job
        steps:
            - run: echo "Repo is ${{github.repository}} ${{env.My_HOST}}"  
    deploy-job:
        runs-on: ubuntu-latest
        needs: test-job
        steps:
            - run: echo "deploy job to production server ${{job.status}}"  